# Generated by Django 5.2.17 on 2026-08-10 10:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enclosures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('diet_category', models.CharField(choices=[('HERBIVORE', 'Herbivore'), ('CARNIVORE', 'Carnivore')], max_length=20)),
                ('food_type', models.CharField(help_text='e.g. Hay, Raw Meat, Fruits', max_length=100)),
                ('quantity_per_feeding_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('feedings_per_day', models.PositiveSmallIntegerField()),
                ('feeding_times', models.JSONField(default=list, help_text='List of "HH:MM" strings')),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_removed', models.DateTimeField(blank=True, null=True)),
                ('enclosure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupants', to='enclosures.enclosure')),
            ],
            options={
                'ordering': ['-date_added'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('enclosure',), name='one_active_occupant_per_enclosure')],
            },
        ),
    ]
